# Generated by Django 4.2.20 on 2026-09-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('internal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('avg_rating', models.FloatField()),
            ],
            options={
                'verbose_name': 'point of interest',
                'verbose_name_plural': 'points of interest',
                'ordering': ('internal_id',),
                'indexes': [models.Index(fields=['category', 'internal_id'], name='poi_category_id_idx')],
            },
        ),
    ]
